### ISSUE TITLE
Loja can list all Proposta per Carro and refuse or accept it 

### ISSUE THREAD

**Issue by pedro-salviano** [IvanCalvo/dsw-1#19]
When logged as Loja must be able to see every Proposta of all theirs Carro, and must be able to refuse or accept it.

When refusing can optionaly send another Proposta.

**Comment by pedro-salviano** [comment]
Loja can list all Proposta per Carro done, missing refuse or accept it

**Comment by Klebaum** [comment]
É possível atualizar o status da Proposta, no entanto, os caminhos acabam levando a outra posta. Para verificar tive que voltar a página de listagem das propostas manualmente e dar um refresh na página.
